### ISSUE TITLE
Make "someone tell me to" cooldown user-specific

### ISSUE THREAD

**Issue by bsoyka** [brainbotdev/brainbot#1]
For example, user `bobsmith`'s cooldown on the autoresponse should be separate from user `johndoe`'s cooldown, meaning they can each use it every 5 minutes.

**Comment by yohanesgultom** [comment]
I'm proposing a simple method to allow user-specific cooldowns with minimal changes. Not sure if it's too hacky. What do you think?

**Comment by bsoyka** [comment]
I like it! I left a review for you. 😃
