### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by LukeG294** [brainbotdev/brainbot#18]
A voting feature where when someone says !vote, BrainBot sets up a poll with custom options. By either reacting to BrainBot's message or sending a message (not sure which is easier), BrainBot will announce the poll results.

**Comment by LukeG294** [comment]
#20 May work for this.

**Comment by LukeG294** [comment]
@bsoyka Maybe we should take another look at this one. What do you think about the idea?

**Comment by Thromax** [comment]
I think I can fix this one, can I take it? I've already have a preliminary version that parses the command and creates a reaction-based poll (still doesn't check the results, I'm on it) .

**Comment by LukeG294** [comment]
That would be amazing, I've been working on it and couldn't figure it out.
