### ISSUE TITLE
Reward/karma system

### ISSUE THREAD

**Issue by bsoyka** [brainbotdev/brainbot#19]
*(Original idea by @LukeG294 in #17)*

### Starting thoughts
* Make a database file to store user points/karma
* Start with a thank command for others to say thanks to each other and give them a point (or something similar)
* Give users points for using commands

**Comment by LukeG294** [comment]
Working on this one using MongoDB. I'll update here as I make progress.

**Comment by LukeG294** [comment]
Will likely finish by 11/20
