### ISSUE TITLE
Translator command

### ISSUE THREAD

**Issue by LukeG294** [brainbotdev/brainbot#29]
A translator command for BrainBot where the bot gathers input from a user and translates their message into a selected language.

This might help: https://pypi.org/project/translate/

**Comment by bsoyka** [comment]
Sounds like a great idea to me!

To whoever would like to work on this: please leave a comment here before starting work on a PR to ensure there are no duplicate PRs.

**Comment by LukeG294** [comment]
Making PR.

**Comment by LukeG294** [comment]
Made PR #34. Removing help labels for now.
