### ISSUE TITLE
Configurable cooldowns

### ISSUE THREAD

**Issue by bsoyka** [brainbotdev/brainbot#38]
The user running the bot should be able to create a `brainbot.ini` file that is parsed with [`configparser`](https://docs.python.org/3/library/configparser.html). Take this as an example of a complete `brainbot.ini` file for now:

```ini
[cooldowns]
tell_me_to=200
topic=100
```

If a value isn't provided for a key or the `brainbot.ini` file doesn't exist, the cooldown values currently in `main.py` can be used as defaults.

The `brainbot.ini` file should also be added to the top of the `.gitignore` file.

**Comment by yohanesgultom** [comment]
Looks easy and fun. Could you review my first pull request?
