### ISSUE TITLE
NATO Phonetic Alphabet 

### ISSUE THREAD

**Issue by DarianAmin** [brainbotdev/brainbot#46]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Using PyPI project "phonetic-alphabet 0.1.0", I would like to integrate a converter to convert a users message that uses !phon into the NATO phonetic alphabet. 

**Describe alternatives you've considered**
Using python to split the message into characters and inputting them into a list. Then it would go through multiple selection statements to convert it into a sentence. The output would be converted to a string and then sent.

**Comment by DarianAmin** [comment]
i would like to be able to do this

**Comment by LukeG294** [comment]
@DarianAmin Could you please clarify the intention of this? Maybe bsoyka understands this a little more than I do but I can't seem to find what is trying to be achieved here. Do you mind providing me with an example input and output?

**Comment by bsoyka** [comment]
Example input: `abc`

Example output: `alpha bravo charlie`

**Comment by LukeG294** [comment]
I see, would it always come out to the same output? Or if I ran abc twice would it show 2 different phrases?

**Comment by DarianAmin** [comment]
Yes exactly

**Comment by bsoyka** [comment]
It would be the same output every time. https://en.wikipedia.org/wiki/NATO_phonetic_alphabet

**Comment by LukeG294** [comment]
Okay, thanks for the clarification. As long as Ben's okay with it I think that'd be a nice idea to implement but somewhat low priority :)

**Comment by DarianAmin** [comment]
However, the project also allows for the conversion of numbers. 

For example: 

290

Two niner zero

**Comment by bsoyka** [comment]
Go for it!

**Comment by DarianAmin** [comment]
> Example input: `abc`
> 
> Example output: `alpha bravo charlie`

Yes, exactly.

**Comment by DarianAmin** [comment]
> Go for it!

Thanks
