### ISSUE TITLE
Timer Command

### ISSUE THREAD

**Issue by LukeG294** [brainbotdev/brainbot#47]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A user could say !timer x hours x minutes x seconds and BrainBot would display a timer starting at that time. Each second it could edit it's message using the pyryver edit message feature. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bsoyka** [comment]
Maybe rather than editing the message every second, we find a way to just ping the user when the time is up.

**Comment by LukeG294** [comment]
> Maybe rather than editing the message every second, we find a way to just ping the user when the time is up.

Great idea, working on that now.

**Comment by LukeG294** [comment]
Running final tests, will be making PR within the next hour @bsoyka
