### ISSUE TITLE
Trivia 

### ISSUE THREAD

**Issue by DarianAmin** [brainbotdev/brainbot#55]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The questions and answers would be on a text file, while, the program randomly indexes them and awaits a response. After, it will check against the answers and say who got it correct. This will run with the command ```!trivia```

**Comment by LukeG294** [comment]
Sounds like a good idea to me!

**Comment by DarianAmin** [comment]
If it is possible can someone help me. I have been having some problems.

The array would delete half way.

**Comment by LukeG294** [comment]
@DarianAmin Can you confirm that the file is opening? Just an idea but maybe it can't find the keywords (answers) as it cannot read the file.

**Comment by DarianAmin** [comment]
I can confirm it is reading the file correctly. This is because it has shown to already be inputted into the array. However, the problem is that the array wiped itself.
