### ISSUE TITLE
Define Function

### ISSUE THREAD

**Issue by LukeG294** [brainbotdev/brainbot#60]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A define function, where when a user says !define and then a word, BrainBot could define that word using a dictionary module of some sort. 

**Describe alternatives you've considered**
N/A

**Additional context**
Low priority.

**Comment by DarianAmin** [comment]
Using the PyDictionary module I would like to add the ability to dictionary (define words), find synonyms and to find antonyms of words. This would run with the commands !define,!synonyms and !antonyms.

**Comment by LukeG294** [comment]
Assigning Darian per request. 

Notes:

I could not use the PyDictionary module properly. There seems to be a problem when importing it. Go ahead and give it a try though.

You can also web scraper dictionary.com if you'd like, that might work better,

**Comment by DarianAmin** [comment]
I will give them both a try.
