### ISSUE TITLE
Dictionary, synonyms and antonyms  

### ISSUE THREAD

**Issue by DarianAmin** [brainbotdev/brainbot#63]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Using the PyDictionary module I would like to add the ability to dictionary (define words), find synonyms and to find antonyms of words. This would run with the commands ```!define```,```!synonyms``` and ```!antonyms```.

**Comment by DarianAmin** [comment]
I would like to be able to do this

**Comment by LukeG294** [comment]
@DarianAmin I have already created an issue similar to this. Please expand on that one :) #60
