### ISSUE TITLE
Random emoticon

### ISSUE THREAD

**Issue by LukeG294** [brainbotdev/brainbot#66]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
!emoticon provides a random, funny emoticon.

**Comment by LukeG294** [comment]
This code might work for it. I am not able to run BrainBot so if someone else could adapt this code/their own code and make a PR that would be awesome :)

```
# Random Emoticon
                elif msg.text.lower().startswith("!emoticon"):
                    emoticons = ["( ͡❛ ͜ʖ ͡❛)","O_o","（　´_ゝ`）","(╯°□°）╯︵ ┻━┻",":-)","<(o_o<)","(/^▽^)/","(•‿•)"]
                    console.log(f"Giving {user.get_username()} a random emoticon.")
                    await send_message(random.choice(emoticons), bot_chat)
```

**Comment by Thromax** [comment]
I've tested your code and works fine so far, should I add a pull request?

**Comment by LukeG294** [comment]
That would be great :)
