### ISSUE TITLE
Send emoticons in code formatting

### ISSUE THREAD

**Issue by bsoyka** [brainbotdev/brainbot#73]
For the `!emoticon` command, all emoticons should be sent in an inline code block (wrapped with backticks) to preserve any characters that have meaning in Markdown.

This also means that any emoticons with backticks should be removed, at least until we come up with a better way to do this.

**Comment by LukeG294** [comment]
I'll take this one if you don't mind @bsoyka

**Comment by bsoyka** [comment]
Sure, go for it!
