### ISSUE TITLE
!repeat allows command injection

### ISSUE THREAD

**Issue by Thromax** [brainbotdev/brainbot#76]
**Describe the bug**

Inputting another command inside `!repeat` arguments will lead to that command execution, allowing users to make the bot run certain commands by itself.

**To Reproduce**

Inserting any command inside `!repeat`. Example: `!repeat !command`

**Expected behavior**

The bot should just run `!repeat`, ignoring the injected command.

**Screenshots**

![botissue](https://user-images.githubusercontent.com/20110319/96749983-c76c8980-13cb-11eb-82ac-ad63578403f3.PNG)

**Additional context**

It seems there is no verification whatsoever that prevents the bot from reading itself when listening for new commands.

**Comment by Thromax** [comment]
I'm not sure if this could be a security issue, in that case please move this issue to the correct category.

**Comment by LukeG294** [comment]
Working on this one.

**Comment by LukeG294** [comment]
Okay now I'm *actually* working on this one 🚀

**Comment by bsoyka** [comment]
Hey, @Thromax! I realize this is a bit late, but after a bit of thought, I'm going to delete this issue and make it a private security advisory until it's fixed. Just don't want to expose this too much as it could potentially be used to cause a whole lot of spam in Ryver organizations that use the bot. Thanks for reporting it though!
