### ISSUE TITLE
Jokes

### ISSUE THREAD

**Issue by DarianAmin** [brainbotdev/brainbot#80]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Have the program simply pull jokes from a text file. I could also have it display the response after a x second delay. The command will run using ```!joke```

**Comment by DarianAmin** [comment]
I would like to have the opportunity to work on it.

**Comment by bsoyka** [comment]
I don't think this is a necessary feature to implement at this time. Maybe we can revisit this in the future.
