### ISSUE TITLE
Heads or Tails

### ISSUE THREAD

**Issue by DarianAmin** [brainbotdev/brainbot#82]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
using the random module I would like to have it pick a number between 0 and 1. This would then represent heads or tails.

**Comment by LukeG294** [comment]
Sounds good @DarianAmin

**Comment by LukeG294** [comment]
I'd wait to see what Ben says but I think that'd be a fun little feature.

**Comment by DarianAmin** [comment]
Sure!👍
