### ISSUE TITLE
LaTeX Error

### ISSUE THREAD

**Issue by LukeG294** [brainbotdev/brainbot#88]
**Describe the bug**
Plus sign is not recognized.

**To Reproduce**
Use a equation with a + sign in a latex command.

**Expected behavior**
Program should take + sign into account.

**Screenshots**

<img width="354" alt="image" src="https://user-images.githubusercontent.com/62516707/98048703-1b6f6900-1de3-11eb-983f-ae95000b0337.png">

**Comment by bsoyka** [comment]
It appears this is an issue with how Ryver renders the link in chat -- click on the link and you'll see the correctly rendered LaTeX. (It seems Ryver converts `%20` to `+` in image links 🤔)

Maybe we need to find another way to render LaTeX in the first place, I'll look into it a bit.

**Comment by bsoyka** [comment]
Fixed in 3e1ba392c534628e1125edc745ba4a5c4fef1c10
