### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by DarianAmin** [brainbotdev/brainbot#94]
**Describe the solution you'd like**
Using the schedule reminder PyPI module I would like to be able to integrate the ability to schedule yourself reminders that will ping you at a certain date or time.

**Comment by DarianAmin** [comment]
I would like to be able to work on this

**Comment by bsoyka** [comment]
I'd rather not recreate something that's already available as a built-in feature on Ryver. Also, that's not really what that module is for, it appears to be for scheduling desktop notifications.
